"""Evidence report generator — forensic reports in JSON/HTML."""

from __future__ import annotations

import json
import datetime
from pathlib import Path
from typing import Any

REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MID Forensic Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }
  h1 { border-bottom: 3px solid #c00; padding-bottom: 0.5rem; }
  h2 { color: #333; margin-top: 2rem; }
  .meta { background: #f5f5f5; padding: 1rem; border-radius: 4px; margin: 1rem 0; }
  .meta dt { font-weight: bold; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }
  th { background: #f0f0f0; }
  .member { background: #ffe0e0; }
  .non-member { background: #e0ffe0; }
  .summary-box { display: flex; gap: 1rem; margin: 1rem 0; }
  .stat { background: #f8f8f8; padding: 1rem; border-radius: 4px; flex: 1; text-align: center; }
  .stat .value { font-size: 2rem; font-weight: bold; color: #c00; }
  .stat .label { font-size: 0.85rem; color: #666; }
  .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #888; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>🔍 MID Forensic Report</h1>

<div class="meta">
<dl>
  <dt>Generated</dt><dd>{{ generated }}</dd>
  <dt>Model</dt><dd>{{ model }}</dd>
  <dt>Attack Type</dt><dd>{{ attack_type }}</dd>
  <dt>Threshold</dt><dd>{{ threshold }}</dd>
</dl>
</div>

<h2>Summary</h2>
<div class="summary-box">
  <div class="stat"><div class="value">{{ total }}</div><div class="label">Total Samples</div></div>
  <div class="stat"><div class="value">{{ members }}</div><div class="label">Members Detected</div></div>
  <div class="stat"><div class="value">{{ avg_conf }}</div><div class="label">Avg Confidence</div></div>
</div>

<h2>Sample Results</h2>
<table>
<tr><th>#</th><th>Text (truncated)</th><th>Score</th><th>Member?</th></tr>
{{ rows }}
</table>

<div class="footer">
  Generated by <strong>MID — Membership Inference Defense</strong> v0.1.0<br>
  This report is for forensic analysis purposes. Results are probabilistic, not deterministic.
</div>
</body>
</html>
"""


def _render_html(evidence: dict[str, Any]) -> str:
    """Render evidence as HTML report."""
    rows = ""
    for i, sample in enumerate(evidence.get("samples", []), 1):
        css_class = "member" if sample.get("is_member") else "non-member"
        rows += f'<tr class="{css_class}"><td>{i}</td><td>{sample.get("text", "")}</td>'
        rows += f'<td>{sample.get("score", 0):.4f}</td>'
        rows += f'<td>{"YES" if sample.get("is_member") else "no"}</td></tr>\n'

    summary = evidence.get("summary", {})
    html = REPORT_HTML_TEMPLATE
    html = html.replace("{{ generated }}", datetime.datetime.now(datetime.timezone.utc).isoformat())
    html = html.replace("{{ model }}", evidence.get("model", "unknown"))
    html = html.replace("{{ attack_type }}", evidence.get("attack_type", "unknown"))
    html = html.replace("{{ threshold }}", str(evidence.get("threshold", 0.8)))
    html = html.replace("{{ total }}", str(summary.get("total_samples", 0)))
    html = html.replace("{{ members }}", str(summary.get("members_detected", 0)))
    html = html.replace("{{ avg_conf }}", f'{summary.get("avg_confidence", 0):.4f}')
    html = html.replace("{{ rows }}", rows)

    return html


def generate_report(evidence_path: str, output_path: str, fmt: str = "json") -> None:
    """Generate a forensic report from evidence data."""
    with open(evidence_path) as f:
        evidence = json.load(f)

    # Enrich with metadata
    report_data = {
        "report_version": "1.0",
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "tool": "membership-inference-defense",
        "tool_version": "0.1.0",
        **evidence,
    }

    output = Path(output_path)

    if fmt == "html":
        output.write_text(_render_html(report_data))
    else:
        output.write_text(json.dumps(report_data, indent=2))
